sudo: required

language: node_js

node_js:
  - "9.5.0"

git:
  depth: 2

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/caffeine
    - IMAGE_TAG=travis-ci-test
    - IMAGE=${IMAGE_REPO}:${IMAGE_TAG}

before_script:
  - npm install -g @angular/cli

install:
  - npm install
  - ng build

cache:
  directories:
  - "$HOME/.npm"

script:
  - ng lint
  - ng test

before_deploy:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh
  - docker build -t ${IMAGE_REPO}:${TRAVIS_COMMIT::12} -t ${IMAGE_REPO}:${TRAVIS_BRANCH} .
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: jmx7elhGC3AGrk+wap82SjKaGgIBvJjjYwhAIkVSVHHgUnujigud8K59uoEHs4o1GMD/ZIrAOCtxrobpeWxMgu6UNTheDHjhr/LmD2t+Skr/wlPd7YdN4N2NEErv2fGnhNNjreC58mk5HzXyTpGLsK1AZYryNH9q2QAeUO3IeqgGlf0g9HsS5Ld0gqeOprxVPwNoeaSp9g9FWbQEt+Axq3SGDy1UkY1G66cId0Fji5lVIsrTXBNLhciNrRsNcRC3iNH9cFeb3jwK6jePKeAPFTtI36bxMa3ZUnPHDLH40NBF7DSauWoX1sKH6xiJ/0TMSBf6zkYyRgr87w5bdF+RyTtuElKXU3c9X3XHIzYnBwg+QutMB9ne+wbChzAphlM3ehS4S0TgHu0FFa2TILIkTYdPwoBUw+IAZij+wDIbRC9oPYEk9toFYAnsi9HXBy5CUnsQwoWVeVI+Nh9y75Zs1CUse7Axd/pZVLzapBkPnyBRZ+utYVd3LiQ1yo8R52mU57KQaaF4Ot9eWRjjLBFr62QVlJgV5aHGOV8kHqrdRLSiZY/sVC1aSJ7XEscVuhywNSqjNv1lDxF7qXb0ddbU1zJt3eoXqTJRV6KVANdSZJSOKHkEOxkK1i1Qy9eN7wCrPTsGvMqE0U4dMrQjTv/V1+dTR0T8SJG88jXlWM+RqTE=
    on_success: change
    on_failure: change
    on_pull_requests: false
