sudo: required

addons:
  chrome: stable

language: node_js

node_js:
  - "9.5.0"

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/caffeine
    - IMAGE_TAG=travis-ci-test
    - IMAGE=${IMAGE_REPO}:${IMAGE_TAG}

before_install:
  - npm install -g @angular/cli
  - npm i -g npm@6.1.0

install:
  - npm ci

cache:
  directories:
  - "$HOME/.npm"

script:
  - node scripts/transpileMd.js src/app/app-welcome/app-welcome.content.md src/app/app-welcome/app-welcome.content.html
  - ng lint
  - ng test --watch false
  - ./scripts/create_sentry_release.sh
  - ./scripts/verify_license_headers.sh src
  - ./scripts/build.sh
  - node ./scripts/post-build.js
#  - ./scripts/push_sentry_sourcemaps.sh

before_deploy:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh
  - docker build -t ${IMAGE_REPO}:${TRAVIS_COMMIT::12} -t ${IMAGE_REPO}:${TRAVIS_BRANCH} .
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: "F1lhMzaf7O6wuRyf++HlieIviHBz13/7Lx6zLxPugaj6ykhyihI6K1Ys5SOMwPng307voo9whPk2vB2mIQg5FTpYv58eN9n7oH8t7i6BaG7nK0uJDzD5M1EpEsoHReObx4qF6/TyQDgR/Q3xGgCYCgN9Yp9f34AYY3Hl1HNIJUmUZebi/LjZnHXQK2dk6FNIJSwtBb6L39z5eGlNAY6mqQvH+QTsPKtD8aD52ECkRxgThQsKPaebelD++ZC9krDd/my65LcxbdYL5ENkuA5a4dUcnrls3B1PqFLrIDOWqeoqghVyyQGo6wbKTbocCvUuJHyCKW5LGRZ5XCDkrCY9faY2x0oTJ4bCOBpvSUCPvJBL8LEZOk+VBmx87hcYryNHktOV8lbtJsIvRWFhyOXNjQ4jdmYzqe30Z6qhtY0OBg1dMjf+M5WPyix2p7Vn12OfzSl4mEifPV1rYtaR/3O4RLO0AQFmiVw9PCiOcmxleRt7dH6lC0mP5i2fj80Ss34m1cc6Am0FYF3DlqbPKD7y54jk1RRWudvIcRotCplMMzPd4hq7VEWgFcDsrh2QCmjAE40WljTCwG3QGUt8Mz1b1MVGbZPUdsGlt6QoNMQDHeqbjPt6Cdbc3n50wa/Bd66VMFIt9Wsb0R9a+17+wnqxebqCLXJ+QhMkGlvtaekAYbo="
    on_success: change
    on_failure: change
    on_pull_requests: false
