apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: caffeine-angular
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - previous.dd-decaf.eu
    secretName: decaf-tls
  rules:
  - host: previous.dd-decaf.eu
    http:
      paths:
      - path: /
        backend:
          serviceName: caffeine-angular
          servicePort: 80
